<a href="https://colab.research.google.com/github/Huyrua27/Exercise/blob/main/Pytorch0_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
#Tạo tensor ngẫu nhiên (7,7)
import torch

random_tensor = torch.rand(7,7)
print(random_tensor)

tensor([[0.8427, 0.5293, 0.7054, 0.2738, 0.2202, 0.7664, 0.7759],
        [0.1268, 0.5552, 0.5128, 0.9999, 0.8191, 0.5092, 0.3252],
        [0.3001, 0.6353, 0.7503, 0.3015, 0.9431, 0.6886, 0.5176],
        [0.6985, 0.4326, 0.2728, 0.1949, 0.4790, 0.9576, 0.8689],
        [0.1595, 0.1049, 0.6360, 0.4550, 0.2546, 0.7728, 0.4109],
        [0.5565, 0.9028, 0.2486, 0.6102, 0.8888, 0.8750, 0.5207],
        [0.0282, 0.1672, 0.9417, 0.2123, 0.2488, 0.4988, 0.2538]])


In [9]:
#Phép nhân ma trận

second_tensor = torch.rand(1, 7)
print(second_tensor)
res = torch.matmul(random_tensor, second_tensor.T)
print(res)

tensor([[0.0637, 0.4237, 0.0928, 0.2896, 0.5341, 0.9038, 0.6685]])
tensor([[1.7517],
        [1.6956],
        [1.9174],
        [2.0118],
        [1.3546],
        [2.2314],
        [0.9749]])


In [10]:
#seed
torch.manual_seed(0)

random_tensor_seed =  torch.rand(7, 7)
print("Tensor 1:")
print(random_tensor_seed)

sedrandomseed = torch.rand(1, 7)
print("Tensor 2:")
print(sedrandomseed)

result = torch.matmul(random_tensor_seed, sedrandomseed.T)
print("Result :")
print(result)

Tensor 1:
tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
Tensor 2:
tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]])
Result :
tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


In [3]:
import torch
#Đặt seed cho GPU
torch.cuda.manual_seed(1234)

torch.manual_seed(1234)

tensor_1 = torch.rand(2, 3)
tensor_2 = torch.rand(2, 3)

if torch.cuda.is_available():
  tensor_1 = tensor_1.to('cuda')
  tensor_2 = tensor_2.to('cuda')
  print("All tensor have been moved to GPU")
else:
  print("GPU is not available")

print("Tensor_1", tensor_1)
print("Tensor_2", tensor_2)


All tensor have been moved to GPU
Tensor_1 tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
Tensor_2 tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')


In [4]:
#Phép nhân matrix trên gpu

matrix_product = torch.matmul(tensor_1, tensor_2.T)
print("Result:", matrix_product)

Result: tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')


In [6]:
#MIN MAX

maxval = torch.max(matrix_product)
minval = torch.min(matrix_product)

print("Max value is ", maxval.item())
print("Min value is ", minval.item())

Max value is  0.5617256760597229
Min value is  0.3647301495075226


In [7]:
#Max min Index

maxindex = torch.argmax(matrix_product)
minindex = torch.argmin(matrix_product)

print("Max index is ", maxindex.item())
print("Min index is ", minindex.item())

Max index is  3
Min index is  0


In [8]:
#Tạo tensor và loại bỏ shape có kích thước 1
torch.manual_seed(7)

tensor_with_ones = torch.rand(1, 1, 1, 10)
print("Tensor ban dau:", tensor_with_ones)
print("Shape ban dau: ", tensor_with_ones.shape)

#Loại bỏ shape 1

squeezed_tensor = tensor_with_ones.squeeze()
print("Tensor sau khi loại bo shape 1 ", squeezed_tensor)
print("Shape sau khi squeeze: ", squeezed_tensor.shape)

Tensor ban dau: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
Shape ban dau:  torch.Size([1, 1, 1, 10])
Tensor sau khi loại bo shape 1  tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
Shape sau khi squeeze:  torch.Size([10])
